### PR TITLE
[Design system sync] Refactoring all colours to follow design system

### PR DESCRIPTION
**Pull request by nicklee**
Ticket URL: n/a

## About these changes

This brings the majority of the build colours inline with the design system, ensuring we're being consistent going forward, and making it easier to use the correct colours.

## How to check these changes

Where possible, provide guidance to help your reviewer

## Before assigning to reviewer, please make sure you have

- [ ] Checked things thoroughly before handing over to reviewer.
- [ ] Checked PR title starts with ticket number as per project conventions to help us keep track of changes.
- [ ] Ensured that PR includes only commits relevant to the ticket.
- [ ] Waited for all CI jobs to pass before requesting a review.
- [ ] Added/updated tests and documentation where relevant.

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

### CODE REVIEW

**Comment by janehughes** [comment]
Noticed a couple of display issues cropped up in search following colour changes:

image

image

Probably makes sense to fix these in this PR?

**Review by janehughes — CHANGES_REQUESTED** [review]
The styling changes all look good - I've done a review locally and added a few screenshots where the colours need tweaking based on the changes. Feels worth updating these here-  I didn't find too many but there might be others.

Thanks for doing this Nick! 👍

**Comment by nicklee** [comment]
I've just fixed all of the above, looks like $color__grey-800 was used to replace some lighter example of colours and this has now been fixed.

**Comment by nicklee** [comment]
I've just merged develop in and addressed the highlighted issues @janehughes, we should be good to go

**Review by janehughes — APPROVED** [review]

**Review by janehughes — APPROVED** [review]

**Pull request merged**
