### PR TITLE
UN-489: Update ArticlePage to utlise TopicalPageMixin

### PR DESCRIPTION
**Pull request by ababic**
Ticket URL: https://national-archives.atlassian.net/browse/UN-489

## About these changes

In this PR:
- A data migration to copy the existing `topic` and `time_period` values over to the `PageTopic` and `PageTimePeriod` link tables, then removes the original fields.
- Another migration to remove the old `topic` and `time_period` fields
- Changes to `get_datalayer_data()` to include multiple topic and time period names joined by a semi-colon
- Replaced the old `templates/includes/related-ce-content.html` include template with the one that was newly created for Record articles (reducing duplication)

## How to check these changes

I guess the only thing I'm uncertain about here is the include/component change for the topic and time period links. Does this look okay on your machine?

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly before handing over to reviewer.
- [x] Checked PR title starts with ticket number as per project conventions to help us keep track of changes.
- [x] Ensured that PR includes only commits relevant to the ticket.
- [x] Waited for all CI jobs to pass before requesting a review.
- [x] Added/updated tests and documentation where relevant.

### CODE REVIEW

**Comment by jamesbiggs** [comment]
Hi Andy, I'm getting this error:

image

When trying to access the `/admin` page. I've deleted and rebuilt my containers etc, and it's doing the same thing. Do I need to run any extra commands or anything?

**Comment by ababic** [comment]
@jamesbiggs Have you run `python manage.py migrate`?

**Comment by jamesbiggs** [comment]
@ababic yeah, I ran it after building everything - but it gets run by `fab pull-staging-data` by default as well

**Comment by ababic** [comment]
@jamesbiggs Looks like you may have a different version of Wagtail installed or something. It doesn't look like anything to do with these changes specifically

**Comment by jamesbiggs** [comment]
@ababic I shouldn't do - I completely deleted all my containers/images/volumes and rebuilt it from your branch. I'll have a look :)

**Comment by jamesbiggs** [comment]
@ababic I'm running wagtail 4.1.2, same as this branch/PR. Just deleted and rebuilt again, getting the same outcome..

**Review by jamesbiggs — APPROVED** [review]
BE code looks good, coming through nicely in the promote tab 👍 

When I view the page live though, this happens:

image

Seems to be unrelated to the changes here, I believe Will is working on the FE here? If so - all good to go! 😄

**Pull request merged**
