### PR TITLE
DSRC-42: Reference/footnote

### PR DESCRIPTION
**Pull request by jamesbiggs**
Ticket URL: [DSRC-42]

## About these changes

Adds a reference block to the GeneralPage (essentially just rich text with different styling)

In the CMS:
image

In the API:
image

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly before handing over to reviewer
- [x] Checked PR title starts with ticket number as per project conventions to help us keep track of changes
- [x] Ensured that PR includes only commits relevant to the ticket
- [x] Waited for all CI jobs to pass before requesting a review
- [x] Added/updated tests and documentation where relevant

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

[DSRC-42]: https://national-archives.atlassian.net/browse/DSRC-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ahosgood** [comment]
https://national-archives.atlassian.net/browse/DSRC-41 suggests we need:

> Reference: Author, Title, Page range, Publication date/Date accessed (title could also be a link if there is a digital version/it is a digital reference)

Also, does this need to allow multiple items or not?

**Comment by jamesbiggs** [comment]
> https://national-archives.atlassian.net/browse/DSRC-41 suggests we need:
> 
> > Reference: Author, Title, Page range, Publication date/Date accessed (title could also be a link if there is a digital version/it is a digital reference)

I asked about having individual fields for each part of a reference, or just a free text field, and Lizzy said a free text field would be best 🙂 

> Also, does this need to allow multiple items or not?

Good point - I hadn't thought about multiple references! I will bring this up later at the check-in - I really think it should be restricted to working off of fields, rather than free text. Too many inconsistencies could occur... 😬

**Comment by ahosgood** [comment]
The reason I ask is because I might need to format the references as a list which I can't do with a single rich text.

We might need to be able to link to a single reference in the list.

**Comment by ahosgood** [comment]
@jamesbiggs - I think we can drop this PR and remove the branch now we have another way forward

**Pull request closed without merging**
