### PR TITLE
Release 4.0.0 into main

### PR DESCRIPTION
**Pull request by jamesbiggs**
## Merging a release branch?

1. Use the `Create a merge commit` option to preserve the original commit IDs.
2. Use the message format `release/<major.minor.patch>` when merging.

f14039a6 Add `data-link="Read"` to featured article (#671)
10a73b3b Add `www.` to relevant links in footer section (#669)
f4a1e04a update search buckets with consistent labelling (#676)
feb8e594 update filter button toggle to always display number of active filters & remove aria-label so SR users hear the button content (#675)
7373a71f adjusting breakpoint for Filters button (#678)
2deee160 Spacing adjustment on mobile/tablet view (#677)
9b8fa06f update icons with new icon includes on detail page for better contrast in high contrast mode (#663)
c531634f update background colour of search filters section (#664)
738eed65 UN-478: Upgrade Python to 3.10 (#646)
2a5e6d3c UN-471: Fix RecordArticlePage still using 'standfirst' instead of 'intro' (#665)
50495af8 Merge pull request #662 from nationalarchives/feature/DF-516-search-label-adjustment
22f8dda3 updating label for search input
c9059f0a Un 387 record revealed fixes (#661)
0a02b4ac Update record article page from internal review (#658)
2e5c0ea9 [DF-519] Update 'show results from' select box to resize to screen width (#660)
39bf3135 add in number of search results to page title and include skip to results page link (#652)
b5721637 UN-471: Separate teaser text and page standfirsts/subtitles (#653)
9d5d8e11 Un 387 frontend record revealed (#641)
a036b4be UN-328: Highlights gallery page BE (#650)
5ede4a2e [DF-515] SR-only mobile menu label (#632)
775922b5 CHORE: Improve Rich Text option consistency (#649)
62c337ee CHORE: Developer QOL changes (#582)
878c533c create new icon include for better styling control and improve sort by icons styles for high contrast accessibility (#644)
36f31a94 UN-482: Upgrade Wagtail to version 4.1.2 (#635)
0c443a42 UN-411:Remove calls to rename_app post deployment (#639)
d06ffc95 CHORE: Update fab command to clear the new renditions table instead of the old one (#640)

[DF-519]: https://national-archives.atlassian.net/browse/DF-519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ababic** [comment]
@jamesbiggs Worth holding out for a little while until all of this has been tested in develop?

**Review by TNA-Allan — COMMENTED** [review]
@jamesbiggs [CI check for python has failed](https://github.com/nationalarchives/ds-wagtail/actions/runs/4308173706/jobs/7514134078). Kind of weird that its got into 9 checks instead of 6. I tried running a test on a local merge which worked fine.

**Comment by ababic** [comment]
@jamesbiggs This seemed fine when I looked at it. It might just be GitHub getting confused. It might be worth closing this PR then resubmitting?

**Comment by jamesbiggs** [comment]
Hi @ababic @TNA-Allan, the CI checks are also somehow failing on develop, even though they passed on develop (you can't merge without them passing) and they had passed on this PR yesterday..?

Screenshot of develop branch CI checks
image

**Comment by jamesbiggs** [comment]
Closing to see if it will fix tests

**Pull request closed without merging**
