### PR TITLE
EDEV-51: Block page data serialization

### PR DESCRIPTION
**Pull request by jamesbiggs**
Ticket URL: [EDEV-51] and [EDEV-50]

## About these changes

Added an `APIPageChooserBlock` which serializes the given page data to output extra field values. As some pages may not have field X I have used a few try/except blocks to counter this, e.g. if we're querying against `wagtailcore.Page` we will get an AttributeError because Page does not have `type_label` or `is_newly_published` or `teaser_image`.

## How to check these changes

http://localhost:8000/api/v2/pages/55/ is quite a good one - it has a few PageChooserBlocks on it, but there are different pages with different variations of PageChooserBlock.

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly before handing over to reviewer
- [x] Checked PR title starts with ticket number as per project conventions to help us keep track of changes
- [x] Ensured that PR includes only commits relevant to the ticket
- [x] Waited for all CI jobs to pass before requesting a review
- [x] Added/updated tests and documentation where relevant

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

[EDEV-51]: https://national-archives.atlassian.net/browse/EDEV-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[EDEV-50]: https://national-archives.atlassian.net/browse/EDEV-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jamesbiggs** [comment]
@ahosgood We can specify different image renditions for each use of APIPageChooser - default is `fill-600x400`.

Let me know if any of these need changing/adding 😄

**Review by ahosgood — APPROVED** [review]

**Review by ahosgood — CHANGES_REQUESTED** [review]
Actually, we need the page description/teaser text

**Comment by jamesbiggs** [comment]
Good spot @ahosgood!
I'm going to split this out into a function so we can have this logic on the blocks and on serializers too (for similar_items/latest_items), and I'm going to make it so that we can pick the fields we want to come back in certain scenarios. Sometimes we might not want images, type_label, or sometimes we may want a specific field such as article tags too.

**Comment by ahosgood** [comment]
Also also, could we apply the same data to the main `featured_article`?

**Comment by jamesbiggs** [comment]
Closed as it is being done by https://github.com/nationalarchives/ds-wagtail/pull/1610

**Pull request closed without merging**
