### PR TITLE
CHORE: Update merge step 

### PR DESCRIPTION
**Pull request by TNA-Allan**
Ticket URL: N/A

## About these changes
Not all of us have the access to deploy to develop environment on platform-sh. This PR suggests if you do not have access, kindly post in the appropriate slack channel for deployment to develop once the PR is merged. Any of us who has access would deploy to develop at the earliest.

## How to check these changes

Action at the time of merge

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly before handing over to reviewer.
- [x] Checked PR title starts with ticket number as per project conventions to help us keep track of changes.
- [x] Ensured that PR includes only commits relevant to the ticket.
- [x] Waited for all CI jobs to pass before requesting a review.
- [x] Added/updated tests and documentation where relevant.

## Merging a feature or bug fix?

1. Use the `Squash and merge` option to keep the target branch's commit history nice and clean.
2. Where relevant, include the ticket number in commit title, e.g. `DF-XXX: Ticket name / short description`.

## Merging a release branch?

1. Use the `Create a merge commit` option to preserve the original commit IDs.
2. Use the message format `release/<major.minor.patch>` when merging.

## Deployment guidance

1. Post to the appropriate Slack channel to check that it is okay to continue.
2. To start a deployment, push the relevant branch to the `platform` remote.
3. Update the appropriate Slack channel when the deployment is complete.
4. Update the status on the corresponding Jira ticket (where relevant).

### CODE REVIEW

**Review by jamesbiggs — CHANGES_REQUESTED** [review]
Maybe "Once PR is merged, contact someone with environment access to arrange a deployment"?

If not, this is fine :) Cheers Allan

**Comment by ababic** [comment]
Personally, I've grown to dread seeing this content again on every PR. Docs are really the place for this level of detail.

**Comment by TNA-Allan** [comment]
> Once PR is merged, contact someone with environment access to arrange a deployment

Looks fine. Updated 👍

**Comment by TNA-Allan** [comment]
> Personally, I've grown to dread seeing this content again on every PR (and I've already programmed my brain to ignore the rendered version on other people's PRs). Docs are really the place for this level of detail.

Could you suggest where to place them ? Should we provide links from here?

**Comment by ababic** [comment]
> Could you suggest where to place them?

@TNA-Allan How do you feel about https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/?

>  Should we provide links from here?

Yep, sure. Maybe this and the deployment process stuff can be linked to in one simple paragraph?

**Comment by TNA-Allan** [comment]
> > Could you suggest where to place them?
> 
> @TNA-Allan How do you feel about https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/?
> 
> > Should we provide links from here?
> 
> Yep, sure. Maybe this and the deployment process stuff can be linked to in one simple paragraph?

Thanks @ababic , Will update the deployment process stuff if this is merged first.

**Review by jamesbiggs — APPROVED** [review]
Hi Allan, brilliant, looks good :) Cheers!

**Pull request merged**
