### PR TITLE
UN-530: Large link cards block

### PR DESCRIPTION
**Pull request by ababic**
Ticket URL: https://national-archives.atlassian.net/browse/UN-530

## About these changes

See ticket description

## How to check these changes

The new block type should be available instances of `TopicExplorerIndexPage` and `TimePeriodExplorerIndexPage`. If you have pulled data from staging, you should be able to see it in action on the following pages:
- https://develop-sr3snxi-rasrzs7pi6sd4.uk-1.platformsh.site/admin/pages/53/edit/
- https://develop-sr3snxi-rasrzs7pi6sd4.uk-1.platformsh.site/admin/pages/54/edit/

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly before handing over to reviewer.
- [x] Checked PR title starts with ticket number as per project conventions to help us keep track of changes.
- [x] Ensured that PR includes only commits relevant to the ticket.
- [x] Waited for all CI jobs to pass before requesting a review.
- [x] Added/updated tests and documentation where relevant.

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

### CODE REVIEW

**Review by jamesbiggs — CHANGES_REQUESTED** [review]
Hey @ababic, nice work, just three things:

1. I can add more than one "Large Link Card" blocks to the page (i.e. link to more than two pages). If you suspect there might be use for this, I'm happy to agree, but I think there should only be a max of one "LLC" block be added to any page.
2. Could you add a `clean()` function here to handle the page requirements? Currently if I pick a page that isn't live, or doesn't have a `teaser_image`, the link won't display on the page. Could you add something to flag this to editors here before publishing/saving?
3. I can link to the page itself (e.g. Topic index page with a link to the topic index page), do you think it's worth adding something to prevent this (I guess this could also go in the clean function?) Or should we leave it to editors to just not pick the wrong page

**Comment by ababic** [comment]
@jamesbiggs
1. Yes, sure
2. Doing this with custom validation is more hassle than it's work. I think it's quite valid for draft pages to be selected as items when the page itself is in draft. The validation status for THIS page shouldn't change based on actions outside of this page.
3. Who's to say selecting the same page is not valid? That sounds like an editor concern - not a developer one.

**Review by jamesbiggs — APPROVED** [review]
Cheers for the replies Andy, happy to accept then 😃

**Comment by ababic** [comment]
@jamesbiggs on point 1: This limitation is already in place here: https://github.com/nationalarchives/ds-wagtail/pull/787/files#diff-77f9be071e806cd9f860f84c66e0169275c090d4518676c454198b4a239a4666R97

**Pull request merged**
