### PR TITLE
UN 720 - collection explorer and stories placement of breadcrumbs 

### PR DESCRIPTION
**Pull request by krishan-torchbox**
Ticket URL: paste URL here

## About these changes

Add a human-readable description here

## How to check these changes

Where possible, provide guidance to help your reviewer

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly before handing over to reviewer.
- [x] Checked PR title starts with ticket number as per project conventions to help us keep track of changes.
- [x] Ensured that PR includes only commits relevant to the ticket.
- [ ] Waited for all CI jobs to pass before requesting a review.
- [ ] Added/updated tests and documentation where relevant.

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

### CODE REVIEW

**Review by janehughes — COMMENTED** [review]
This is looking brilliant thanks Krishan!

I feel we should have a chat with Leanne about this change before it gets merged to develop. It's generally looking good in the Collection Explorer/Stories pages, but I've noticed by adjusting the header container and breadcrumbs it's flagged up issues with body containers in other page types - notably across the 'Search' section (which makes sense given we haven't been focussing on those templates) and I also spotted that the topic & time period index pages are also using the wrong body container - e.g. http://localhost:8000/explore-the-collection/explore-by-time-period/early-modern/

So before I approve & merge this I just want to check if we should also update those other containers in this PR, rather than raising another ticket to cover them separately

**Review by jamesbiggs — CHANGES_REQUESTED** [review]
Hi Krishan, nice work but a few changes needed here 🙂 

http://localhost:8000/explore-the-collection/explore-by-time-period/early-modern/ has no breadcrumb anymore

Should be:
image

Currently:
image

Also looks like the menu bar has shifted over but it looks like it's matching the designs, but as that isn't part of this ticket (i.e. we might not want that) could we remove that too please?

**Comment by ahosgood** [comment]
Just had to push a small fix to this (sorry!)

1. Resize window to mobile width
2. Open menu
3. Resize back to desktop size
4. Try and find the menu

**Comment by krishan-torchbox** [comment]
@jamesbiggs the adjustments of the menu bar on desktop was due to the comms on the ticket from last week when we discovered the inconstant placement of nav elements, breadcrumbs and content.
https://national-archives.atlassian.net/browse/UN-720

We probably should of raised it as separate tickets but do you still want to revert some of those changes so it just meets the AC for the ticket?

**Review by ahosgood — APPROVED** [review]
Approving assuming comments from @jamesbiggs are addressed

**Comment by jamesbiggs** [comment]
> @jamesbiggs the adjustments of the menu bar on desktop was due to the comms on the ticket from last week when we discovered the inconstant placement of nav elements, breadcrumbs and content. https://national-archives.atlassian.net/browse/UN-720
> 
> We probably should of raised it as separate tickets but do you still want to revert some of those changes so it just meets the AC for the ticket?

Sorry @krishan-torchbox, I didn't see that! If it's been talked about then that's fine! 😄

**Review by jamesbiggs — CHANGES_REQUESTED** [review]
Hi Krishan,

I see the breadcrumbs on all of the pages now and they are all in the same place, nice work :) 

However, the menu bar is behaving differently

Current site in tablet view:
image

These changes: 
image

Current site in mobile view:
image

These changes:
image

**Review by jamesbiggs — APPROVED** [review]
Nice work Krishan :)

**Pull request merged**
