### PR TITLE
Update frontend styles, use assets from package

### PR DESCRIPTION
**Pull request by ahosgood**
- Update `@nationalarchives/frontend` from `0.1.16-prerelease` to `0.1.20-prerelease` (https://github.com/nationalarchives/tna-frontend/compare/v0.1.16-prerelease...v0.1.20-prerelease)
- Add new footer
- Abstract card HTML to separate component template
- Remove multiple image sizes from cards (saves on bandwidth and processing)
- Move cookie banner up above header and don't overlay the content
- Fix cookie banner width to not be wider than the page on some devices
- Fix promoted article width
- Audio heading and transcript colour fix
- Update npm packages
- Update Python packages

### CODE REVIEW

**Comment by JohnHeeryTNA** [comment]
`sass/etna.scss`

line 324

`#ds-cookie-consent-banner {
    padding: 1rem 0 !important;
    position: static !important;
    background: #134571 !important;
    border-radius: 0 !important;

    .container {
        padding: 0 0 10px !important;
    }
}`

Do we need these !important;'s?

**Comment by JohnHeeryTNA** [comment]
templates/includes/card-group-secondary-nav.html
line 3

```
- {% image link_page.teaser_image fill-288x172 as teaser_image_small %}
- {% image link_page.teaser_image fill-328x196 as teaser_image_medium %}
- {% image link_page.teaser_image fill-348x208 as teaser_image_large %}
- {% image link_page.teaser_image fill-508x304 as teaser_image_extra_large %}
+ {% image link_page.teaser_image fill-800x450 as card_image %}

I _believe_ that this is Wagtails method for serving images dependant on screen size - smaller images (kb) for smaller viewports. Do we want to keep this method or use this alternative?  



```

**Comment by ahosgood** [comment]
@JohnHeeryTNA

To get the icons, you have to rebuild the container as there is a command to copy in the icons: https://github.com/nationalarchives/ds-wagtail/blob/48e01db4a26cb814ec9ed281d96025a9a18534b6/Dockerfile#L20-L22

I've added the `!important` rules into `#ds-cookie-consent-banner` for now to fix some layout issues but with the intention that they will be taken out once the new cookie banner is good to go: https://nationalarchives.github.io/tna-frontend/?path=/story/components-cookie-banner--standard

With the responsive images, the difference in dimensions between them all was so small that I didn't feel there was any benefit to resizing them on the fly. Plus the amount of data transferred as you resized the window and requested all four sizes easily added up to more than just serving a single, better quality image. We could either have 4x ~50KB images or 1 ~80KB image so I went with that one.

**Comment by JohnHeeryTNA** [comment]
Thanks @ahosgood for the feedback. 

- I'll rebuild my containers to double check the icons. 
- With you on the !important rules for now
- image logic makes sense, just wanted to check.

**Review by JohnHeeryTNA — APPROVED** [review]
approving changes

**Pull request merged**
