### PR TITLE
DF-726: Feedback mechanism updates [BE]

### PR DESCRIPTION
**Pull request by ababic**
Ticket URL:  https://national-archives.atlassian.net/browse/DF-726

## About these changes

Add a human-readable description here

## How to check these changes

Where possible, provide guidance to help your reviewer

## Before assigning to reviewer, please make sure you have

- [ ] Checked things thoroughly before handing over to reviewer.
- [ ] Checked PR title starts with ticket number as per project conventions to help us keep track of changes.
- [ ] Ensured that PR includes only commits relevant to the ticket.
- [ ] Waited for all CI jobs to pass before requesting a review.
- [ ] Added/updated tests and documentation where relevant.

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

### CODE REVIEW

**Comment by TNA-Allan** [comment]
> Hi @TNA-Allan. Could I request a review here from you from a BE perspective? Someone else should be reviewing/changing the JS stuff here, so there's not much value in fussing over that at this stage.

From the BE perspective it looks good. I don't have the capacity to review FE,JS.

> Someone else should be reviewing/changing the JS stuff here

Is this something pending?

I did some testing on local and found these potential issues
1) When JS is disabled, I was not able to see the comments box
2) Comments gets saved without pressing submit button
   With the FE branch with this PR, 
   when comments are entered and the Comments box is closed with X, the comment gets saved.

**Review by TNA-Allan — COMMENTED** [review]
Some queries above for you @ababic

**Comment by ababic** [comment]
> When JS is disabled, I was not able to see the comments box

This is an intentional trade-off to help guard against spam.

> Comments gets saved without pressing submit button

One to look at in the FE PR I would expect.

**Comment by ababic** [comment]
Would you be happy to approve this one, @TNA-Allan ?

**Review by TNA-Allan — APPROVED** [review]

**Pull request merged**
