### PR TITLE
Update TNA Frontend

### PR DESCRIPTION
**Pull request by ahosgood**
Changes from v0.1.23-prerelease to v0.1.43: https://github.com/nationalarchives/tna-frontend/compare/v0.1.23-prerelease...v0.1.43

- https://national-archives.atlassian.net/browse/EDEV-21
- https://national-archives.atlassian.net/browse/UN-822
- Implemented new pagination component for search

### CODE REVIEW

**Review by jamesbiggs — APPROVED** [review]
All looks good to me @ahosgood! Just one question - why did you have to comment out the `show_beta_banner` tests?

**Review by jamesbiggs — CHANGES_REQUESTED** [review]
Actually, sorry, one small thing on the search pages...

Develop/main:
image

This branch:
image

**Comment by ahosgood** [comment]
@jamesbiggs 

> All looks good to me @ahosgood! Just one question - why did you have to comment out the `show_beta_banner` tests?

Because I'm an idiot and commented them out becasue I set `FEATURE_BETA_BANNER_ENABLED=False` in the `docker-compose.yml` which means the test fails locally 🤦🏼‍♂️

Good spot on the search results - I didn't do a very good job of conflict resolution on the latest merge from `develop`.

Anyway, a 3/10 for me on attention to detail on this one...

**Review by jamesbiggs — APPROVED** [review]
🚀

**Comment by tm-kn** [comment]
@ahosgood Does it make sense to comment out the CSS code rather than just delete it given we can recover it from the Git diff?

**Pull request merged**
