### PR TITLE
UN 742 hero image banner text area leaving the banner area

### PR DESCRIPTION
**Pull request by krishan-torchbox**
Ticket URL: [UN-742](https://national-archives.atlassian.net/browse/UN-742)

## About these changes

Added line clamp and text overflow to reduce the content on the intro when resizing 

## How to check these changes

Create a page with a highlight intro and fill out the intro paragraph with the max number of characters (300)
Expected results: 
Mobile - no change
Tablet - Intro paragraph will be truncated to 2-3 lines
Desktop - no change

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly before handing over to reviewer.
- [x] Checked PR title starts with ticket number as per project conventions to help us keep track of changes.
- [x] Ensured that PR includes only commits relevant to the ticket.
- [ ] Waited for all CI jobs to pass before requesting a review.
- [ ] Added/updated tests and documentation where relevant.

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

[UN-742]: https://national-archives.atlassian.net/browse/UN-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jamesbiggs — CHANGES_REQUESTED** [review]
Hi Krishan, sorry, this is still happening on the pages

image

**Review by jamesbiggs — APPROVED** [review]
Hey Krishan, I think we might need to do this a different way

image

The text is still leaving the area (it's hard to see as it's not going over the breadcrumb, but it's there)

Also some of the first lines of text are being hidden under the title (see the little black lines above the introduction)

I understand I've probably gone past the constraints of both fields on their max_lengths, but the main pain here is the use of `bottom` and the hard-set `width`. I'm not really sure of a way to change this though 🙁

**Comment by ahosgood** [comment]
We might have to re-look at this component. I have done a mock up of something that doesn't break (https://nationalarchives.github.io/tna-frontend/?path=/story/components-hero--standard). Could we use some of this HTML and CSS until this component is usable within ETNA?

**Comment by ahosgood** [comment]
I wonder if this might be a better approach: https://github.com/nationalarchives/ds-wagtail/pull/1127

**Comment by krishan-torchbox** [comment]
Superseded by https://github.com/nationalarchives/ds-wagtail/pull/1127

**Pull request closed without merging**
