### PR TITLE
EDEV-85: local dev run updates

### PR DESCRIPTION
**Pull request by TNA-Allan**
Ticket URL: https://national-archives.atlassian.net/browse/EDEV-85

## About these changes

- remove migrate step to fix local build setup when internal migrations are updated
- relocate and create superuser on pulling data
```
NOTE: Any Django users you were using before will no longer exist.
Creating superuser with credentials setup from docker compose.
Superuser created successfully.
```

```
NOTE: Any Django users you were using before will no longer exist.
Creating superuser with credentials setup from docker compose.
*** Failed to create superuser *** 
You may want to run `python manage.py createsuperuser` from a container shell to create yourself a new one.
```

## How to check these changes

```
fab build
fab start
fab pull-[staging/production]-data
```

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly before handing over to reviewer
- [x] Checked PR title starts with ticket number as per project conventions to help us keep track of changes
- [x] Ensured that PR includes only commits relevant to the ticket
- [x] Waited for all CI jobs to pass before requesting a review
- [x] Added/updated tests and documentation where relevant

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

### CODE REVIEW

**Comment by ahosgood** [comment]
The original reason I added the run migrations in `run-dev.sh` was to emulate updating the container on a live service - the migrations get run when the application starts.

Would it not make more sense to NOT run migrations when we pull the data (so we have a perfect copy of the live DB state) and then only run migrations when you start the service?

**Comment by ahosgood** [comment]
For reference, this is how live will do it: https://github.com/nationalarchives/docker/blob/98b519c4612213a7ecc15f746e17f7026cc25fd3/docker/tna-python-django/bin/tna-run

**Comment by TNA-Allan** [comment]
> Would it not make more sense to NOT run migrations when we pull the data (so we have a perfect copy of the live DB state) and then only run migrations when you start the service?

I think this would happen, when we want to apply locally made database changes on a new refresh of data.

**Comment by TNA-Allan** [comment]
> The original reason I added the run migrations in run-dev.sh was to emulate updating the container on a live service - the migrations get run when the application starts.

Would run-dev.sh also run on a non-local i.e. hosted environment?

**Review by jamesbiggs — APPROVED** [review]
Works good for me! 🚀

**Review by ahosgood — APPROVED** [review]

**Pull request merged**
