### PR TITLE
TNA Python Docker image

### PR DESCRIPTION
**Pull request by ahosgood**
Switched over to using a base Docker image for Django applications (https://github.com/nationalarchives/docker/tree/main/docker/tna-python-django) which takes away a lot of application-specific configuration from the `Dockerfile` and results in faster build times.

There are also now images for both AMD and ARM architectures.

Disabled the Django debug toolbar by default as this was adding >5MB to each page load, slowing down the whole application locally. It can be re-enabled by adding `DEBUG_TOOLBAR=true` to your `.env`

The `AUTO_START_SERVER` environment variable for automatically starting the development script for CSS and JavaScript building has been replaced with `NPM_DEVELOP_COMMAND=dev`. If not defined, watching and rebuilding of the SCSS and JavaScript files will not happen.

To stop the application running migrations and starting the server automatically (if you want manual control) you can comment out the commands in `bash/run-dev.sh`. The application should still start but just do nothing and wait for your commands. From here you could start the server yourself:

```sh
# Open a shell into the web application
fab sh

# Run the application with the installed run script...
tna-run config.wsgi:application
# ...or run the migrations and use the Django development server
poetry run python /app/manage.py migrate && poetry run python /app/manage.py runserver 0.0.0.0:8080
```

There is a new container called "dev" (which you can log into with `fab dev`) that offers the following commands:

```
==========================================
ETNA Dev Commands
------------------------------------------

help
  Display all commands (this file)

makemigrations
  Create all DB migrations using Django

createsuperuser
  Create a superuser using Django

update-npm
  Update all npm packages and write the changes back to package.json and package-lock.json

update-poetry
  Update all Poetry packages and write the changes back to pyproject.toml and poetry.lock

manage
  Run any Django command against the manage.py file

build
  Compile all the application JavaScript and CSS

build-js
  Compile the application JavaScript

build-css
  Compile the application CSS

dev
  Compile the application JavaScript and CSS and watch for changes (runs in the background)

dev-js
  Compile the application JavaScript and watch for changes

dev-css
  Compile the application CSS and watch for changes

==========================================
```

### CODE REVIEW

**Review by jamesbiggs — COMMENTED** [review]
Hi AJ - I like this work, everything works fine when I run it, however, I can't seem to make migrations
```cmd
app@20a801b73f5a:/app$ python manage.py makemigrations
Migrations for 'articles':
  etna/articles/migrations/0097_remove_focusedarticlepage_author.py
    - Remove field author from focusedarticlepage
Traceback (most recent call last):
  File "/app/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/home/app/.cache/pypoetry/virtualenvs/etna-9TtSrW0h-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/app/.cache/pypoetry/virtualenvs/etna-9TtSrW0h-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/app/.cache/pypoetry/virtualenvs/etna-9TtSrW0h-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/app/.cache/pypoetry/virtualenvs/etna-9TtSrW0h-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/etna-9TtSrW0h-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.cache/pypoetry/virtualenvs/etna-9TtSrW0h-py3.11/lib/python3.11/site-packages/django/core/management/commands/makemigrations.py", line 259, in handle
    self.write_migration_files(changes)
  File "/home/app/.cache/pypoetry/virtualenvs/etna-9TtSrW0h-py3.11/lib/python3.11/site-packages/django/core/management/commands/makemigrations.py", line 363, in write_migration_files
    with open(writer.path, "w", encoding="utf-8") as fh:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/app/etna/articles/migrations/0097_remove_focusedarticlepage_author.py'
```

or use `npm run compile:css` 
```cmd
app@20a801b73f5a:/app$ npm run compile:css

> ds-wagtail@7.5.1 compile:css
> sass --quiet-deps --load-path=node_modules sass/etna.scss:templates/static/css/dist/etna.css

Error reading templates/static/css/dist/etna.css.map: permission denied.
```

JS compiles fine though!

I can always just add `USER root` to the Dockerfile... Or could we have some sort of "dev docker image" and a "production docker image", both doing the same thing but one runs as root, the other as app? Or something similar! 😃

**Comment by ahosgood** [comment]
I have now introduced a new container (`dev_helper`) to replace the two `poetry_update` and `npm_update` containers.

You can get into it using `fab dev`. From there, you can run `help` to show you all the available commands:
image

This will allow you to do things like update Poetry (with `update-poetry`) and not run into permissions issues on Windows machines.

This will hopefully also be the container that we can use to pull the latest database snapshot and media from the preview environment (once we make the move to AWS).

**Review by jamesbiggs — COMMENTED** [review]
Hi AJ, I've just given this a go - a few things with this one:
`makemigrations` works once, then when trying to make the migrations again, it wouldn't detect any further changes from the first run.

If I run `manage migrate` from the `dev` terminal, it seems to run every migration - which would've already been run when I did `fab pull-staging-data`. Running it again doesn't seem to run them all again. However, if I do `fab sh` and then `python manage.py migrate` it runs the newly created migration (which I already ran in the `fab dev`).

`update-npm`:
```
# update-npm
Found '/app/.nvmrc' with version <v18.16>
v18.16.1 is already installed.
Now using node v18.16.1 (npm v9.5.1)
/home/app/.local/bin/dev/update-npm: line 4: npm: command not found
```

`update-poetry`: Updates dependencies and writes the lock file, but doesn't actually apply the updates. e.g. `wagtail 5.1 -> 5.1.1` has no effect

`dev-css and dev-js`: Works, but they both output this twice:
```
v18.16.1 is already installed.
Now using node v18.16.1 (npm v9.5.1)
Now using node v18.16.1 (npm v9.5.1)
``` 

`build`: Same as above, outputs `Now using node v18.16.1 (npm v9.5.1)` twice.

`dev`: Same as above, but outputs `Now using node v18.16.1 (npm v9.5.1)` four times.

`fab dev`: `manage runserver 0:8000` and `fab sh`: `python manage.py runserver 0:8000`: Both work, tested site and everything seems to be running.

Apologies if I've missed anything 😃

**Comment by ahosgood** [comment]
@jamesbiggs - Thank you so much for doing all that testing!

`makemigrations` and `manage migrate`
These should now work. I was an idiot and forgot to connect the `dev` container to the database! 🤦🏼‍♂️

I would ignore the multiple `Now using node v18.16.1 (npm v9.5.1)` messages. I know they're annoying but I've added the nvm check in a few places to ensure that everyone is always using the same version. I will look to make this a bit better in the future.

`update-npm`
This now works but there may be another `Now using node v18.16.1 (npm v9.5.1)` message (sorry!)

`update-poetry`
This will just update the lock file in line with the versions defined in `project.toml` but not change those versions - that's for you to decide and do manually. From https://python-poetry.org/docs/cli/#update:

> Note that this will not update versions for dependencies outside their version constraints specified in the pyproject.toml file. In other terms, poetry update foo will be a no-op if the version constraint specified for foo is ~2.3 or 2.3 and 2.4 is available. In order for foo to be updated, you must update the constraint, for example ^2.3. You can do this using the add command.

I don't think I ever intended to be able to run the server from within the `dev` container but because it's essentially a copy of the main container, I don't see why you couldn't. 🤔

**Comment by jamesbiggs** [comment]
Cool, thank you AJ! 😃 

> `update-poetry` This will just update the lock file in line with the versions defined in `project.toml` but not change those versions - that's for you to decide and do manually. From https://python-poetry.org/docs/cli/#update:

On this one, I meant that it is getting the latest versions that we have allowed allowed in the `pyproject.toml` ✅  and then writing the `poetry.lock` file with the new versions ✅ but then it doesn't actually update the packages locally for you - it only updates the lock file. I tested this with wagtail - The current version is 5.1.0 in the `poetry.lock` and the `pyproject.toml` is at ~5.1 which would allow for 5.1.1. Running `update-poetry` gets 5.1.1, updates `poetry.lock`, but doesn't actually apply the update/new version

**Comment by ahosgood** [comment]
@jamesbiggs - Changed this now so that `poetry-update` will update all the deps in the `dev` container and once that succeeds, apply the same update to the `web` container. 🤞🏼

**Comment by jamesbiggs** [comment]
`update-npm`: Seems to have worked but I get this error at the end of it `OCI runtime exec failed: exec failed: unable to start container process: exec: "source": executable file not found in $PATH: unknown`

`update-poetry`: Worked and installed packages but failed to install Wagtail. I ran it again and it worked on the second go. I killed everything and started again just to be sure and everything worked the first time - I assume it was just a hiccup 😃

**Comment by ahosgood** [comment]
@jamesbiggs - I should have squashed that (hopefully) last issue now?

**Comment by jamesbiggs** [comment]
I'm now getting:
```
# update-npm
Found '/app/.nvmrc' with version <v18.16>
v18.16.1 is already installed.
Now using node v18.16.1 (npm v9.5.1)

added 4 packages, changed 51 packages, and audited 649 packages in 24s

52 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice 
Found '/app/.nvmrc' with version <v18.16>
v18.16.1 is already installed.
Now using node v18.16.1 (npm v9.5.1)
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /app/package-lock.json
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, open '/app/package-lock.json'
npm ERR!  [Error: EACCES: permission denied, open '/app/package-lock.json'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/app/package-lock.json'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/app/.npm/_logs/2023-08-22T11_52_12_020Z-debug-0.log
```

Also, a side thing but somewhat relevant here - if we run tests (I did `fab dev` and then `manage test`) it creates a load of image files which aren't ignored by git in the `media` folder. Could we add the `media` folder to the `.gitignore` please? 😄

**Comment by ahosgood** [comment]
@jamesbiggs - I've ignored the `media` directory now.

I've tested every command on the list and they all work for me on my Windows machine using Ubuntu on WSL2. I hope it's the same for you? 🤞🏼

**Comment by jamesbiggs** [comment]
The `update-npm` and `update-poetry` commands are working, however I'm getting an error when trying to use the `wagtailmedia` package under the `admin/media` route. If I try editing one of the media files, I get this error:
image

I tried it on the `develop` branch and it's working on there and on PlatformSH

**Review by jamesbiggs — APPROVED** [review]
😎

**Pull request merged**
