### PR TITLE
DF 383 remove "search within" and filters in zero results + DF-314

### PR DESCRIPTION
**Pull request by jamesbiggs**
Related ticket(s):
Completes https://national-archives.atlassian.net/browse/DF-383 and https://national-archives.atlassian.net/browse/DF-314

## About these changes

DF-314: Reintroduced website_search.html in the views.py file as we were using catalogue_search.html for both catalogue search and website search views.

DF-383: Changed featured results to hide each individual tab/bucket of results if none are shown. Changed catalogue + website results to hide individual buckets if they have no results, or hide everything and display "no results" message. If the user is still on a bucket which is then hidden by using a different search term, then it will show the available buckets and the "no results" message.

## How to check these changes

Use catalogue, website or featured search to use different search terms. I found that "test", "test search term" and a random string e.g. "huasdhasjdhas" is an effective way of seeing a different number of results.

## Dear reviewer, I promise I have:

- [ ] Checked things thoroughly myself before handing over to you.
- [ ] Included the ticket number in the PR title to help us keep track of changes
- [ ] Ensured that my PR does not include any irrelevant commits.
- [ ] Waited for all CI jobs to pass before requesting a review.
- [ ] Added/updated tests and documentation where relevant.

### CODE REVIEW

**Comment by JohnHeeryTNA** [comment]
Functionality seems fine, however the display of the 'no results' message on mobil looks a little off to me. I'd like @sdwilkes to add his input. Mobile portrait screenshot attached
Screenshot 2022-08-26 at 11 51 51

**Comment by jamesbiggs** [comment]
Hi @JohnHeeryTNA, which search term did you use to get this? This is what I get on a zero results page on mobile view:
image

**Comment by JohnHeeryTNA** [comment]
Hi @jamesbiggs , I used something like 'asasasasahsdahs' it's not the content that is the issue it's the indentation of the bullet points and the title position that I'd like @sdwilkes feedback on.

**Comment by sdwilkes** [comment]
@JohnHeeryTNA @jamesbiggs The title should be left-aligned, with no spacing so it lines up with the paragraph. This should be the same at all breakpoints so it's consistent. Thanks.

**Comment by JohnHeeryTNA** [comment]
Hi @sdwilkes , I've adjusted the paddings for mobile views now, should be displaying correctly.

**Comment by jamesbiggs** [comment]
Hi @sdwilkes all the changes are made now, is this ok to merge? Cheers

**Comment by sdwilkes** [comment]
@jamesbiggs  Can you assign to Mo or Allan to review the python code changes? Thanks.

**Comment by jamesbiggs** [comment]
Hi @TNA-Allan, could you review these changes please? It is mostly changes to the HTML logic (Jinja2) but I also changed the views.py and test_views.py to display the website_search.html instead of catalogue_search.html for Website and Catalogue search views. Cheers :)

**Review by TNA-Allan — APPROVED** [review]
Looks Good!

**Pull request merged**
