### PR TITLE
UN - 723 Fixed font size and removed breakpoints for bigger fonts as in figma …

### PR DESCRIPTION
**Pull request by krishan-torchbox**
…the fonts remain at 16px on desktop & mobile

Ticket URL: paste URL here

## About these changes

Add a human-readable description here

## How to check these changes

Where possible, provide guidance to help your reviewer

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly before handing over to reviewer.
- [x] Checked PR title starts with ticket number as per project conventions to help us keep track of changes.
- [x] Ensured that PR includes only commits relevant to the ticket.
- [ ] Waited for all CI jobs to pass before requesting a review.
- [ ] Added/updated tests and documentation where relevant.

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

### CODE REVIEW

**Comment by krishan-torchbox** [comment]
UN 723
https://national-archives.atlassian.net/browse/UN-723

Local link to test 
/explore-the-collection/the-monteagle-letter/

Fixed font size to 16px for both desktop and mobile as per design

**Review by jamesbiggs — DISMISSED** [review]
Hey Krishan, could we have different font-sizes for different screen sizes please? We want the original size for desktop and tablet view size, and then only the smaller font on mobile view 🙂

**Comment by janehughes** [comment]
Just picking this up on James' behalf - it looks like the font-family needs to be updated as well as font-size. We need to switch to using the standard body font `$font__body` instead of the `$font__supria-sans` we have at the mo.

**Review by janehughes — APPROVED** [review]

**Comment by janehughes** [comment]
Hey @krishan-torchbox could you update this branch with the latest from develop when you get a sec - then we'll get this merged - thanks!

**Pull request merged**
